// Supported version from order older to newer
export const ALL_SUPPORTED_SDK_VERSIONS = ['1.0.0'];

export const LATEST_SUPPORTED_SDK_VERSION =
  ALL_SUPPORTED_SDK_VERSIONS[ALL_SUPPORTED_SDK_VERSIONS.length - 1];

export const OLDEST_SUPPORTED_SDK_VERSION = ALL_SUPPORTED_SDK_VERSIONS[0];
